# Generated by Django 5.0.7 on 2024-09-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="musician_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("First_Name", models.CharField(max_length=75)),
                ("Last_Name", models.CharField(max_length=75)),
                ("Email", models.EmailField(max_length=254)),
                ("Phone_Number", models.IntegerField()),
                ("Instrument_Type", models.CharField(max_length=100)),
            ],
        ),
    ]
