# Generated by Django 5.0.7 on 2024-09-22 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("album", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album_model",
            name="Album_Release_Date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 9, 22, 9, 18, 12, 707088)
            ),
        ),
    ]
